[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "W",
  "I",
  "B",
  "UP",
  "S",
  "PL",
  "C4",
  "TID",
  "SIM",
]
ignore = [
  "E203",
  "E501",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101", "PLR2004"]

[tool.mypy]
python_version = "3.11"
strict = true
ignore_missing_imports = true
warn_unreachable = true
warn_unused_configs = true
exclude = "(?x)(^\\.venv/|^build/|^dist/|^\\.mypy_cache/|^\\.pytest_cache/)"

[[tool.mypy.overrides]]
module = ["tests.*", "tests"]
allow_untyped_defs = true
allow_untyped_calls = true
allow_untyped_globals = true

[[tool.mypy.overrides]]
module = ["*.migrations.*"]
ignore_errors = true

